# Generated by Django 3.1.7 on 2021-04-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminReparapp', '0001_initial'),
        ('AgenteReparapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='tecnico_epecialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminReparapp.tecnicoespecialista'),
        ),
    ]
