# Generated by Django 3.1.7 on 2021-05-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgenteReparapp', '0002_auto_20210427_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('REPARADA', 'Reparado'), ('RECEPCIONADA', 'Recepcionado'), ('EN REPARACIÓN', 'En Reparación'), ('INFORMADA', 'Informada'), ('CERRADA', 'Cerrada')], default='RECEPCIONADA', max_length=20),
        ),
    ]
