# Generated by Django 3.1.7 on 2021-07-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgenteReparapp', '0003_auto_20210501_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
    ]
