# Generated by Django 3.1.7 on 2021-04-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenter',
            fields=[
                ('CallCenter_NIT', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre_callcenter', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CallCenter',
                'verbose_name_plural': 'CallCenters',
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('Taller_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_taller', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Tallers',
            },
        ),
    ]
